services:
  web:
    container_name: django_web
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env.docker
    depends_on:
      - db
      - redis
  db:
    container_name: postgres_db
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.docker
  redis:
    container_name: redis_db
    image: redis:latest
    ports:
      - 6379:6379
    env_file:
      - ./.env.docker
    volumes:
      - redis:/data
  celery:
    container_name: celery
    build:
      context: .
    command: celery -A ForgottenPhotocards worker --loglevel=info
    env_file:
      - ./.env.docker
    depends_on:
      - db
      - redis
  flower:
    container_name: flower
    build:
      context: .
    command: celery -A ForgottenPhotocards flower
    ports:
      - 5555:5555
    env_file:
      - ./.env.docker
    depends_on:
      - db
      - redis
volumes:
  postgres_data:
  redis: