services:
  web:
    container_name: django_web
    volumes:
      - static_volume:/app/web/static
      - media_volume:/app/web/blogdata
    build:
      context: .
      dockerfile: ./Dockerfile_prod
    ports:
      - 8000:8000
    env_file:
      - ./.env.docker
    depends_on:
      - db
      - redis
  db:
    container_name: postgres_db
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.docker
  redis:
    container_name: redis_db
    image: redis:latest
    ports:
      - 6379:6379
    env_file:
      - ./.env.docker
    volumes:
      - redis:/data
  celery:
    container_name: celery
    build:
      context: .
    command: celery -A ForgottenPhotocards worker --loglevel=info
    env_file:
      - ./.env.docker
    depends_on:
      - db
      - redis
  flower:
    container_name: flower
    build:
      context: .
    command: celery -A ForgottenPhotocards flower
    ports:
      - 5555:5555
    env_file:
      - ./.env.docker
    depends_on:
      - db
      - redis
      - celery
  nginx:
    container_name: nginx_web
    image: nginx:latest
    volumes:
      - static_volume:/app/web/static
      - media_volume:/app/web/blogdata
      - ./nginxconf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  static_volume:
  media_volume:
  postgres_data:
  redis: