version: "3.8"

services:
  web:
    container_name: develop_web
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/blogdata
    depends_on:
      - db
      - redis
    command: sh -c "python manage.py collectstatic --no-input &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
  db:
    container_name: develop_db
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
  redis:
    container_name: redis_db
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - redis:/data
  celery:
    container_name: celery
    build:
      context: .
    command: celery -A ForgottenPhotocards worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - redis
  flower:
    container_name: flower
    build:
      context: .
    command: celery -A ForgottenPhotocards flower
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery
volumes:
  static_volume:
  media_volume:
  postgres_data:
  redis: