# Generated by Django 4.2.10 on 2024-03-14 15:32

import blogsite.models
import blogsite.storage
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PictureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ARCHITECTURE', 'Architecture'), ('PORTRAIT', 'Portrait'), ('URBAN', 'Urban'), ('EVENT', 'Event'), ('OTHER', 'Other')], default='OTHER', max_length=12, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grouped_id', models.CharField(max_length=17, unique=True, verbose_name='Служебный ID')),
                ('text', models.TextField(verbose_name='Текст поста')),
                ('camera', models.CharField(blank=True, max_length=256, null=True, verbose_name='Модель камеры')),
                ('lens', models.CharField(blank=True, max_length=256, null=True, verbose_name='Объектив')),
                ('film', models.CharField(blank=True, max_length=256, null=True, verbose_name='Фотопленка')),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_filename', models.CharField(default=None, max_length=256, unique=True, verbose_name='Файл изображения')),
                ('image', models.ImageField(storage=blogsite.storage.OverwriteStorage(), upload_to=blogsite.models.Picture.directory_path, verbose_name='Изображение')),
                ('categories', models.ManyToManyField(blank=True, related_name='categories', to='blogsite.picturecategory')),
                ('picture_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogsite.post', to_field='grouped_id', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['picture_post', 'image_filename'],
            },
        ),
    ]
